[versions]
agp = "8.2.1"
kotlin = "1.9.21"
activityCompose = "1.8.2"
amplitude = "2.37.0"
appcompat = "1.6.1"
composeBom = "2023.10.01"
composeBomBeta = "2023.12.00-alpha04" # we need material3 with ptr support
composeCompiler = "1.5.7"
coreKtx = "1.12.0"
fragmentKtx = "1.6.2"
hilt = "2.48"
hiltNavigationCompose = "1.1.0"
ktlint = "1.1.0"
gradleKtlint = "12.0.3"
serialization = "1.6.1"
ktor = "2.3.6"
lifecycleViewmodelCompose = "2.7.0"
material = "1.11.0"
navigationCompose = "2.7.6"
gms = "22.6.0"
runtime = "1.5.4"
timber = "5.0.1"

storyteller = "9.12.0"

[libraries]
android-sdk = { module = "com.amplitude:android-sdk", version.ref = "amplitude" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-bom-beta = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "composeBomBeta" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtime" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "gms" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

storyteller = { module = "Storyteller:sdk", version.ref = "storyteller" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jetbrainsKotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
jetbrainsKotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradleKtlint" }
